class CreateEsgCores < Apiv2MigrationBase[5.2]
  def change
    create_table :esg_cores do |t|
      t.date :etfg_date
      t.date :as_of_date
      t.string :company_name
      t.column :isin, 'character(12)'
      t.string :region
      t.string :sector
      t.string :industry
      t.decimal :e1, :precision => 22, :scale => 6
      t.decimal :e2, :precision => 22, :scale => 6
      t.decimal :e3, :precision => 22, :scale => 6
      t.decimal :emp1, :precision => 22, :scale => 6
      t.decimal :emp2, :precision => 22, :scale => 6
      t.decimal :emp3, :precision => 22, :scale => 6
      t.decimal :cit1, :precision => 22, :scale => 6
      t.decimal :cit2, :precision => 22, :scale => 6
      t.decimal :cit3, :precision => 22, :scale => 6
      t.decimal :g1, :precision => 22, :scale => 6
      t.decimal :g2, :precision => 22, :scale => 6
      t.decimal :g3, :precision => 22, :scale => 6
      t.decimal :e, :precision => 22, :scale => 6
      t.decimal :s, :precision => 22, :scale => 6
      t.decimal :g, :precision => 22, :scale => 6
      t.decimal :esg, :precision => 22, :scale => 6
      t.decimal :carbon, :precision => 22, :scale => 6
      t.decimal :diversity, :precision => 22, :scale => 6
      t.decimal :controversy, :precision => 22, :scale => 6
      t.decimal :percentile_sector_e1, :precision => 22, :scale => 6
      t.decimal :percentile_sector_e2, :precision => 22, :scale => 6
      t.decimal :percentile_sector_e3, :precision => 22, :scale => 6
      t.decimal :percentile_sector_emp1, :precision => 22, :scale => 6
      t.decimal :percentile_sector_emp2, :precision => 22, :scale => 6
      t.decimal :percentile_sector_emp3, :precision => 22, :scale => 6
      t.decimal :percentile_sector_cit1, :precision => 22, :scale => 6
      t.decimal :percentile_sector_cit2, :precision => 22, :scale => 6
      t.decimal :percentile_sector_cit3, :precision => 22, :scale => 6
      t.decimal :percentile_sector_g1, :precision => 22, :scale => 6
      t.decimal :percentile_sector_g2, :precision => 22, :scale => 6
      t.decimal :percentile_sector_g3, :precision => 22, :scale => 6
      t.decimal :percentile_sector_e, :precision => 22, :scale => 6
      t.decimal :percentile_sector_s, :precision => 22, :scale => 6
      t.decimal :percentile_sector_g, :precision => 22, :scale => 6
      t.decimal :percentile_sector_esg, :precision => 22, :scale => 6
      t.decimal :percentile_sector_carbon, :precision => 22, :scale => 6
      t.decimal :percentile_sector_diversity, :precision => 22, :scale => 6
      t.decimal :percentile_sector_controversy, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_e1, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_e2, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_e3, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_emp1, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_emp2, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_emp3, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_cit1, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_cit2, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_cit3, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_g1, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_g2, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_g3, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_e, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_s, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_g, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_esg, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_carbon, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_diversity, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_sector_controversy, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_e1, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_e2, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_e3, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_emp1, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_emp2, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_emp3, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_cit1, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_cit2, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_cit3, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_g1, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_g2, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_g3, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_e, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_s, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_g, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_esg, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_carbon, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_diversity, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_sector_controversy, :precision => 22, :scale => 6
      t.decimal :percentile_us_e1, :precision => 22, :scale => 6
      t.decimal :percentile_us_e2, :precision => 22, :scale => 6
      t.decimal :percentile_us_e3, :precision => 22, :scale => 6
      t.decimal :percentile_us_emp1, :precision => 22, :scale => 6
      t.decimal :percentile_us_emp2, :precision => 22, :scale => 6
      t.decimal :percentile_us_emp3, :precision => 22, :scale => 6
      t.decimal :percentile_us_cit1, :precision => 22, :scale => 6
      t.decimal :percentile_us_cit2, :precision => 22, :scale => 6
      t.decimal :percentile_us_cit3, :precision => 22, :scale => 6
      t.decimal :percentile_us_g1, :precision => 22, :scale => 6
      t.decimal :percentile_us_g2, :precision => 22, :scale => 6
      t.decimal :percentile_us_g3, :precision => 22, :scale => 6
      t.decimal :percentile_us_e, :precision => 22, :scale => 6
      t.decimal :percentile_us_s, :precision => 22, :scale => 6
      t.decimal :percentile_us_g, :precision => 22, :scale => 6
      t.decimal :percentile_us_esg, :precision => 22, :scale => 6
      t.decimal :percentile_us_carbon, :precision => 22, :scale => 6
      t.decimal :percentile_us_diversity, :precision => 22, :scale => 6
      t.decimal :percentile_us_controversy, :precision => 22, :scale => 6
      t.decimal :quantile_us_e1, :precision => 22, :scale => 6
      t.decimal :quantile_us_e2, :precision => 22, :scale => 6
      t.decimal :quantile_us_e3, :precision => 22, :scale => 6
      t.decimal :quantile_us_emp1, :precision => 22, :scale => 6
      t.decimal :quantile_us_emp2, :precision => 22, :scale => 6
      t.decimal :quantile_us_emp3, :precision => 22, :scale => 6
      t.decimal :quantile_us_cit1, :precision => 22, :scale => 6
      t.decimal :quantile_us_cit2, :precision => 22, :scale => 6
      t.decimal :quantile_us_cit3, :precision => 22, :scale => 6
      t.decimal :quantile_us_g1, :precision => 22, :scale => 6
      t.decimal :quantile_us_g2, :precision => 22, :scale => 6
      t.decimal :quantile_us_g3, :precision => 22, :scale => 6
      t.decimal :quantile_us_e, :precision => 22, :scale => 6
      t.decimal :quantile_us_s, :precision => 22, :scale => 6
      t.decimal :quantile_us_g, :precision => 22, :scale => 6
      t.decimal :quantile_us_esg, :precision => 22, :scale => 6
      t.decimal :quantile_us_carbon, :precision => 22, :scale => 6
      t.decimal :quantile_us_diversity, :precision => 22, :scale => 6
      t.decimal :quantile_us_controversy, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_e1, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_e2, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_e3, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_emp1, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_emp2, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_emp3, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_cit1, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_cit2, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_cit3, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_g1, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_g2, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_g3, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_e, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_s, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_g, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_esg, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_carbon, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_diversity, :precision => 22, :scale => 6
      t.decimal :percentile_us_lg_cap_controversy, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_e1, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_e2, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_e3, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_emp1, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_emp2, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_emp3, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_cit1, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_cit2, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_cit3, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_g1, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_g2, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_g3, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_e, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_s, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_g, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_esg, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_carbon, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_diversity, :precision => 22, :scale => 6
      t.decimal :quantile_us_lg_cap_controversy, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_e1, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_e2, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_e3, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_emp1, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_emp2, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_emp3, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_cit1, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_cit2, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_cit3, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_g1, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_g2, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_g3, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_e, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_s, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_g, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_esg, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_carbon, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_diversity, :precision => 22, :scale => 6
      t.decimal :percentile_us_sm_cap_controversy, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_e1, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_e2, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_e3, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_emp1, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_emp2, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_emp3, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_cit1, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_cit2, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_cit3, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_g1, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_g2, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_g3, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_e, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_s, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_g, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_esg, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_carbon, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_diversity, :precision => 22, :scale => 6
      t.decimal :quantile_us_sm_cap_controversy, :precision => 22, :scale => 6
      t.decimal :forecast_impact_e1, :precision => 22, :scale => 6
      t.decimal :forecast_impact_e2, :precision => 22, :scale => 6
      t.decimal :forecast_impact_e3, :precision => 22, :scale => 6
      t.decimal :forecast_impact_emp1, :precision => 22, :scale => 6
      t.decimal :forecast_impact_emp2, :precision => 22, :scale => 6
      t.decimal :forecast_impact_emp3, :precision => 22, :scale => 6
      t.decimal :forecast_impact_cit1, :precision => 22, :scale => 6
      t.decimal :forecast_impact_cit2, :precision => 22, :scale => 6
      t.decimal :forecast_impact_cit3, :precision => 22, :scale => 6
      t.decimal :forecast_impact_g1, :precision => 22, :scale => 6
      t.decimal :forecast_impact_g2, :precision => 22, :scale => 6
      t.decimal :forecast_impact_g3, :precision => 22, :scale => 6
      t.decimal :forecast_impact_e, :precision => 22, :scale => 6
      t.decimal :forecast_impact_s, :precision => 22, :scale => 6
      t.decimal :forecast_impact_g, :precision => 22, :scale => 6
      t.decimal :forecast_impact_esg, :precision => 22, :scale => 6
      t.decimal :forecast_impact_carbon, :precision => 22, :scale => 6
      t.decimal :forecast_impact_diversity, :precision => 22, :scale => 6
      t.decimal :forecast_impact_controversy, :precision => 22, :scale => 6
      t.decimal :historic_model_ex_market   , :precision => 22, :scale => 6
      t.decimal :historic_model_ex_market_sector, :precision => 22, :scale => 6
      t.decimal :dynamic_model_ex_market, :precision => 22, :scale => 6
      t.decimal :dynamic_model_ex_market_sector, :precision => 22, :scale => 6
    end
  end
end
