#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  pool: 100
  timeout: 5000
  host: 10.10.10.10 #public.etfg.com # 167.99.237.105 # 10.10.10.10
  schema_search_path: apiv2
  database: etfg
  username: etfg
  password: ShortEverything!
    #<%= ENV['API_DB_PASSWORD'] %>

development:
  <<: *default
  #database: etfg_dev

production:
  <<: *default
