# == Schema Information
#
# Table name: esg_ratings
#
#  id                              :bigint(8)        not null, primary key
#  etfg_date                       :date
#  rating_date                     :date
#  composite_ticker                :string
#  e1                              :decimal(22, 6)
#  e2                              :decimal(22, 6)
#  e3                              :decimal(22, 6)
#  emp1                            :decimal(22, 6)
#  emp2                            :decimal(22, 6)
#  emp3                            :decimal(22, 6)
#  cit1                            :decimal(22, 6)
#  cit2                            :decimal(22, 6)
#  cit3                            :decimal(22, 6)
#  g1                              :decimal(22, 6)
#  g2                              :decimal(22, 6)
#  g3                              :decimal(22, 6)
#  e                               :decimal(22, 6)
#  s                               :decimal(22, 6)
#  g                               :decimal(22, 6)
#  carbon                          :decimal(22, 6)
#  diversity                       :decimal(22, 6)
#  controversy                     :decimal(22, 6)
#  percentile_us_e1                :decimal(22, 6)
#  percentile_us_e2                :decimal(22, 6)
#  percentile_us_e3                :decimal(22, 6)
#  percentile_us_emp1              :decimal(22, 6)
#  percentile_us_emp2              :decimal(22, 6)
#  percentile_us_emp3              :decimal(22, 6)
#  percentile_us_cit1              :decimal(22, 6)
#  percentile_us_cit2              :decimal(22, 6)
#  percentile_us_cit3              :decimal(22, 6)
#  percentile_us_g1                :decimal(22, 6)
#  percentile_us_g2                :decimal(22, 6)
#  percentile_us_g3                :decimal(22, 6)
#  percentile_us_e                 :decimal(22, 6)
#  percentile_us_s                 :decimal(22, 6)
#  percentile_us_g                 :decimal(22, 6)
#  percentile_us_esg               :decimal(22, 6)
#  percentile_us_carbon            :decimal(22, 6)
#  percentile_us_diversity         :decimal(22, 6)
#  percentile_us_controversy       :decimal(22, 6)
#  quantile_us_e1                  :decimal(22, 6)
#  quantile_us_e2                  :decimal(22, 6)
#  quantile_us_e3                  :decimal(22, 6)
#  quantile_us_emp1                :decimal(22, 6)
#  quantile_us_emp2                :decimal(22, 6)
#  quantile_us_emp3                :decimal(22, 6)
#  quantile_us_cit1                :decimal(22, 6)
#  quantile_us_cit2                :decimal(22, 6)
#  quantile_us_cit3                :decimal(22, 6)
#  quantile_us_g1                  :decimal(22, 6)
#  quantile_us_g2                  :decimal(22, 6)
#  quantile_us_g3                  :decimal(22, 6)
#  quantile_us_e                   :decimal(22, 6)
#  quantile_us_s                   :decimal(22, 6)
#  quantile_us_g                   :decimal(22, 6)
#  quantile_us_esg                 :decimal(22, 6)
#  quantile_us_carbon              :decimal(22, 6)
#  quantile_us_diversity           :decimal(22, 6)
#  quantile_us_controversy         :decimal(22, 6)
#  forecast_impact_e1              :decimal(22, 6)
#  forecast_impact_e2              :decimal(22, 6)
#  forecast_impact_e3              :decimal(22, 6)
#  forecast_impact_emp1            :decimal(22, 6)
#  forecast_impact_emp2            :decimal(22, 6)
#  forecast_impact_emp3            :decimal(22, 6)
#  forecast_impact_cit1            :decimal(22, 6)
#  forecast_impact_cit2            :decimal(22, 6)
#  forecast_impact_cit3            :decimal(22, 6)
#  forecast_impact_g1              :decimal(22, 6)
#  forecast_impact_g2              :decimal(22, 6)
#  forecast_impact_g3              :decimal(22, 6)
#  forecast_impact_e               :decimal(22, 6)
#  forecast_impact_s               :decimal(22, 6)
#  forecast_impact_g               :decimal(22, 6)
#  forecast_impact_esg             :decimal(22, 6)
#  forecast_impact_carbon          :decimal(22, 6)
#  forecast_impact_diversity       :decimal(22, 6)
#  forecast_impact_controversy     :decimal(22, 6)
#  historic_model_ex_market        :decimal(22, 6)
#  historic_model_ex_market_sector :decimal(22, 6)
#  dynamic_model_ex_market         :decimal(22, 6)
#  dynamic_model_ex_market_sector  :decimal(22, 6)
#

class EsgRating < EtfgDbV2Base
  self.record_timestamps = false
end
